<template>
  <AdminVenueView
    v-model:search-query="searchQuery"
    v-model:filter-status="filterStatus"
    v-model:show-add-modal="showAddModal"
    v-model:show-edit-modal="showEditModal"
    v-model:view-detail-row="viewDetailRow"
    v-model:delete-target="deleteTarget"
    v-model:show-add-edit-confirm="showAddEditConfirm"
    v-model:show-exit-confirm="showExitConfirm"
    v-model:amenity-input="amenityInput"
    :venue-amenities="venueAmenities"
    :success-alert="successAlert"
    :table-container-ref="tableContainerRef"
    :add-edit-confirm-message="addEditConfirmMessage"
    :form="form"
    :venue-detail-images="venueDetailImages"
    :venue-images-for-list="venueImagesForList"
    :filtered-rows="filteredRows"
    :paginated-rows="paginatedRows"
    :showing-from="showingFrom"
    :showing-to="showingTo"
    :current-page="currentPage"
    :total-pages="totalPages"
    @update:form="({ key, value }) => { (form as Record<string, unknown>)[key] = value }"
    @prev="currentPage--"
    @next="currentPage++"
    @close-success-alert="successAlert.show = false"
    @confirm-submit-add="confirmSubmitAdd"
    @confirm-save-edit="confirmSaveEdit"
    @do-confirm-add-or-save="doConfirmAddOrSave"
    @confirm-exit-without-save="confirmExitWithoutSave"
    @open-view-modal="openViewModal"
    @open-edit-modal="openEditModal"
    @close-modals="closeModals"
    @confirm-delete="confirmDelete"
    @do-delete="doDelete"
    @add-amenity-from-input="addAmenityFromInput"
    @remove-amenity="removeAmenity"
  />
</template>

<script setup lang="ts">
definePageMeta({ layout: 'admin' })
const {
  venueAmenities,
  searchQuery,
  filterStatus,
  currentPage,
  totalPages,
  paginatedRows,
  showingFrom,
  showingTo,
  showAddModal,
  showEditModal,
  viewDetailRow,
  deleteTarget,
  successAlert,
  tableContainerRef,
  showAddEditConfirm,
  addEditConfirmMessage,
  showExitConfirm,
  amenityInput,
  form,
  venueDetailImages,
  venueImagesForList,
  filteredRows,
  addAmenityFromInput,
  removeAmenity,
  confirmSubmitAdd,
  confirmSaveEdit,
  doConfirmAddOrSave,
  confirmExitWithoutSave,
  openViewModal,
  openEditModal,
  closeModals,
  submitAdd,
  saveEdit,
  confirmDelete,
  doDelete,
} = useAdminVenuePage()
</script>
